name: Deploy to Dev1

on: workflow_dispatch

jobs:
  lint-and-tests:
    name: Check lint and tests source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages, format, lint
        run: |
          yarn install
          yarn format
          yarn lint

  build-and-deploy:
    name: Bundle source, push image and deploy AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: |
          yarn install

      - name: Bundle source
        run: |
          yarn prebuild
          yarn build

      - name: 'Trigger deployment script on server'
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.DEV1_VM_PRIVATE_KEY }}"
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-251-50-102.ap-southeast-1.compute.amazonaws.com -- "cd deploy-nestjs && git fetch && git checkout ${{ github.head_ref || github.ref_name }} && sudo yarn build && sudo pm2 restart dist/main.js"
